#Type the following in the terminal from the src folder of the project "kk2872-proj3"

	javac AprioriMiner.java

# AprioriMiner.java is the file which has the main() function of the project. 
# The above command compiles AprioriMiner.java.
# Create a directory named src and put the main AprioriMiner.java file in it. This is specified by -sourcepath. 
# Create an empty directory named bin where all compiled *.class files will be created. This is specified by -d. 		
# This file should be in the directory that contains src, lib and bin directories. 

	java AprioriMiner INTEGRATED-DATASET.csv <minSupport> <minConfidence>

#Enter respective values for minSupport and minConfidence.
# The above command specifies how to run AprioriMiner along with the input arguments. Replace them with number of required arguments.
